# server/gemini_service.py
import google.generativeai as genai
import logging
import config # To access default model names

logger = logging.getLogger(__name__)

class GeminiService:
    def __init__(self, api_key):
        if not api_key:
            raise ValueError("Gemini API Key is required for GeminiService.")
        self.api_key = api_key
        genai.configure(api_key=self.api_key)
        logger.info("GeminiService initialized.")

    async def call_gemini_api(self, prompt_text, model_name=None, image_base64=None, image_mime_type=None):
        """
        Calls the Gemini API with the given prompt and optional image data.
        """
        if not model_name:
            model_name = config.GEMINI_DEFAULT_MODEL
        
        logger.info(f"Calling Gemini API with model: {model_name}")
        # logger.debug(f"Prompt: {prompt_text[:500]}...") # Log beginning of prompt

        try:
            model = genai.GenerativeModel(model_name)

            if image_base64 and image_mime_type:
                if "vision" not in model_name.lower() and "flash" not in model_name.lower():  # Basic check, specific model names are better
                    logger.warning(f"Model {model_name} might not be vision-capable. Attempting image send anyway.")
                content = [
                    prompt_text,
                    {
                        "mime_type": image_mime_type,
                        "data": image_base64
                    }
                ]
            else:
                content = prompt_text

            response = await model.generate_content_async(content)

            # Basic safety check (though comprehensive checks are more complex)
            if not response.candidates:
                logger.warning(f"Gemini API returned no candidates. Response: {response}")
                if response.prompt_feedback and response.prompt_feedback.block_reason:
                    raise Exception(
                        f"Prompt blocked: {response.prompt_feedback.block_reason_message or response.prompt_feedback.block_reason}"
                    )
                raise Exception("No candidates returned by Gemini API.")

            first_candidate = response.candidates[0]
            parts = getattr(getattr(first_candidate, "content", None), "parts", None)
            if not parts:
                logger.warning(f"Gemini API returned candidate with no content parts. Response: {response}")
                if response.prompt_feedback and response.prompt_feedback.block_reason:
                    raise Exception(
                        f"Prompt blocked: {response.prompt_feedback.block_reason_message or response.prompt_feedback.block_reason}"
                    )
                finish_reason = getattr(first_candidate, "finish_reason", None)
                if finish_reason is not None and finish_reason != 1:  # 1 = STOP
                    raise Exception(
                        f"Generation stopped due to: {finish_reason}. Safety ratings: {getattr(first_candidate, 'safety_ratings', None)}"
                    )
                raise Exception("No content generated by Gemini API or content was blocked.")

            generated_text = "".join(part.text for part in parts if hasattr(part, "text"))
            logger.info(f"Gemini API call successful for model {model_name}.")
            # logger.debug(f"Generated text: {generated_text[:500]}...")
            return generated_text

        except Exception as e:
            logger.error(f"Error calling Gemini API with model {model_name}: {e}", exc_info=True)
            # Try to get more specific error information if available
            if hasattr(e, 'response') and hasattr(e.response, 'text'):
                logger.error(f"Gemini API Error Response: {e.response.text}")
            raise  # Re-raise the exception to be handled by the caller

    async def stream_gemini_api(self, prompt_text, model_name=None, image_base64=None, image_mime_type=None):
        """
        Streams the Gemini API response, yielding text chunks as they arrive.
        This is an async generator that yields (chunk_text, is_done) tuples.
        """
        if not model_name:
            model_name = config.GEMINI_DEFAULT_MODEL
        
        logger.info(f"Streaming Gemini API with model: {model_name}")

        try:
            model = genai.GenerativeModel(model_name)

            if image_base64 and image_mime_type:
                content = [
                    prompt_text,
                    {
                        "mime_type": image_mime_type,
                        "data": image_base64
                    }
                ]
            else:
                content = prompt_text

            # Stream the response
            response = await model.generate_content_async(content, stream=True)
            
            full_text = ""
            async for chunk in response:
                if chunk.text:
                    full_text += chunk.text
                    yield chunk.text, False
            
            # Signal completion
            yield "", True
            logger.info(f"Streaming complete for model {model_name}. Total length: {len(full_text)}")

        except Exception as e:
            logger.error(f"Error streaming Gemini API with model {model_name}: {e}", exc_info=True)
            yield f"Error: {str(e)}", True

    def parse_initial_generation(self, response_text):
        """
        Parses the combined output from the initial generation prompt into
        clinical note and AI analysis parts.
        """
        if "AI_ANALYSIS_SEPARATOR_V2" in response_text:
            parts = response_text.split("AI_ANALYSIS_SEPARATOR_V2", 1)
            note_text = parts[0].strip()
            analysis_text = parts[1].strip() if len(parts) > 1 else ""
            return note_text, analysis_text
        else:
            logger.warning("AI_ANALYSIS_SEPARATOR_V2 not found in Gemini response. Returning full response as note.")
            return response_text.strip(), "" # Assume everything is the note if separator is missing
